### ISSUE TITLE
error on USB

### ISSUE THREAD

**Issue by pikeupe** [laurentalacoque/TouchSelfie#40]
Hello
I just made the update everything works fine except when I want to saved the photos on the USB key
he tells me:

Traceback (most recent call last):
  File "user_interface.py", line 481, in snap
    os.rename(self.last_picture_filename, new_filename)
OSError: [Errno 18] Invalid cross-device link

thank you for your work and help

**Comment by laurentalacoque** [comment]
Hi @pikeupe 
Good one!
This is an unforeseen limitation of rename. I'll address this when I'm back from holidays next week 😉

**Comment by laurentalacoque** [comment]
# todo
  [ ] change os.rename to shutil.copy and os.remove

**Comment by pikeupe** [comment]
Hello

thank you and have a good holiday

**Comment by laurentalacoque** [comment]
Problem solved in merge #43 
Now available in master.
