### ISSUE TITLE
Print function and effects

### ISSUE THREAD

**Issue by Pikokosan** [laurentalacoque/TouchSelfie#44]
Hi! So we used the original version of this software for my fiancee's wedding shower over the weekend. I was presented with some things that needed to be done better. 

I found your version and its infinitely better.

2 things that I'll be trying to work on are.

#1 adding a button to send photos directly to a cannon selphy cp1300 from the raspberry.

#2 visual effects. Picamera has a image_effects function that has some predefined effects. I would like users to be able to view and pick from them if they wanted. This function is very low on my list.

If anyone has any insight into this help is appreciated. Ofcourse I'll share what I learn here. 

Thanks
  -Pikoko

**Comment by laurentalacoque** [comment]
Hey @Pikokosan 
Thanks for your comment !

- For 1/ do you know if there's a driver for the selphy on raspian?
- For 2/ Nice idea, I'll think about it ;)

**Comment by Pikokosan** [comment]
from what i've been seeing it is possible using CUPS. I found this project https://github.com/zoroloco/boothy/ which says he uses a cp1200. I should know more later this evening.

I saw your last merge! thank you. I plan to put the photos on a flash drive

**Comment by laurentalacoque** [comment]
Printer support added in merge #46 
Thanks @Pikokosan !

**Comment by laurentalacoque** [comment]
# Addressing builtin picamera effects
This is a work in progress in branch [builtin-effects](https://github.com/laurentalacoque/TouchSelfie/tree/builtin-effects)

**Comment by laurentalacoque** [comment]
Builtin effects support now proposed in Pull Request #47
