### ISSUE TITLE
Possible to add sounds?

### ISSUE THREAD

**Issue by jdb1982** [laurentalacoque/TouchSelfie#76]
Is there a way to play a sound right before a picture is taken?

**Comment by laurentalacoque** [comment]
Hello @jdb1982 !

It is possible, I think the best place to implement this is at the end of the countdown function, just after [this line](https://github.com/laurentalacoque/TouchSelfie-extended/blob/ce29c19322561e1116a0d418f9fe04a569e5e893/scripts/user_interface.py#L679)

You'll need to find a way to play a sound file from python.
