### ISSUE TITLE
Linebreak in email body

### ISSUE THREAD

**Issue by djtale** [laurentalacoque/TouchSelfie#84]
Hi Laurent.

This is regarding the email feature.
- how to have linebreak in the mail body ?
- how to handle accent characters (for french) in the subject or body ?
>> I'm currently using this : config.emailMsg.encode('utf-8'), but don't know if this is the best way

Thanks

**Comment by djtale** [comment]
OK,

I just found the answer by myself and I think the best is to use html tags.
It works perfectly.

**Comment by laurentalacoque** [comment]
Glad you found a solution!

If it's not too much to ask, please describe the changes you made in this thread, this might help people with similar issues in the future 😉
